#!/bin/bash

name=proteins
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative False --use_raw_node_label False --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative False --use_raw_node_label False --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative True --use_raw_node_label False --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative False --use_raw_node_label True --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative False --use_raw_node_label False --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative True --use_raw_node_label False --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative True --use_raw_node_label True --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative False --use_raw_node_label True --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative False --use_raw_node_label True --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative False --use_raw_node_label False --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative True --use_raw_node_label False --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative True --use_raw_node_label True --use_node_label False
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree False --set_node_degree_uninformative True --use_raw_node_label True --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative False --use_raw_node_label True --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative True --use_raw_node_label False --use_node_label True
CUDA_VISIBLE_DEVICES=0 python3 -m train.proteins_train_eval --filt_conv_number 1 --num_epochs 2 --batch_size 128 --output_dir ./results --device 0 --exp_name ${name} --use_node_degree True --set_node_degree_uninformative True --use_raw_node_label True --use_node_label True
